# Generated by Django 2.2.15 on 2020-08-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventpage', '0002_auto_20200813_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='persons',
            field=models.ManyToManyField(blank=True, related_name='holding', to='eventpage.Person'),
        ),
        migrations.AddField(
            model_name='event',
            name='persons_modified',
            field=models.BooleanField(default=False),
        ),
    ]
