# Generated by Django 2.2.15 on 2020-08-13 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventpage', '0004_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventpage.Track'),
        ),
        migrations.AddField(
            model_name='event',
            name='track_modified',
            field=models.BooleanField(default=False),
        ),
    ]
