# Generated by Django 2.2.15 on 2020-08-13 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbb', '0004_auto_20200813_1900'),
        ('eventpage', '0005_auto_20200813_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bbb',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_room', to='bbb.Room'),
        ),
    ]
