# Generated by Django 2.2.15 on 2020-08-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventpage', '0006_room_bbb'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='order',
            field=models.IntegerField(default=9000),
        ),
        migrations.AddField(
            model_name='room',
            name='view_size',
            field=models.IntegerField(default=4),
        ),
    ]
