# Generated by Django 2.2.15 on 2020-08-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventpage', '0008_auto_20200813_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
