# Generated by Django 2.2.15 on 2020-08-14 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventpage', '0011_person_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='date_modified',
            new_name='start_modified',
        ),
        migrations.RemoveField(
            model_name='event',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='event',
            name='duration_modified',
        ),
    ]
