# Generated by Django 2.2.15 on 2020-08-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventpage', '0014_auto_20200814_0554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField()),
            ],
        ),
    ]
