# Generated by Django 2.2.15 on 2020-08-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventpage', '0017_announcement_ident'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='abstract_modified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_modified',
            field=models.BooleanField(default=False),
        ),
    ]
