# Generated by Django 2.2.15 on 2020-08-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventpage', '0018_auto_20200814_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='logo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='logo_modified',
            field=models.BooleanField(default=False),
        ),
    ]
