# Generated by Django 2.2.15 on 2020-08-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventpage', '0019_auto_20200814_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='abstract_modified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='description_modified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='image_modified',
            field=models.BooleanField(default=False),
        ),
    ]
