# Generated by Django 3.0.8 on 2020-08-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventpage', '0020_auto_20200814_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='stream',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='HLS Stream URL'),
        ),
        migrations.AddField(
            model_name='room',
            name='stream_moreformats',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Link to page with more streaming formats'),
        ),
    ]
