# Generated by Django 3.0.8 on 2020-08-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventpage', '0021_auto_20200817_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(blank=True, max_length=35, null=True),
        ),
    ]
