# Generated by Django 3.0.7 on 2020-08-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventpage', '0023_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug_modified',
            field=models.BooleanField(default=False),
        ),
    ]
