# Generated by Django 3.0.8 on 2020-08-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventpage', '0024_event_slug_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='custom',
            field=models.BooleanField(default=False, verbose_name='Ignore any overrides from schedule'),
        ),
        migrations.AddField(
            model_name='person',
            name='custom',
            field=models.BooleanField(default=False, verbose_name='Ignore any overrides from schedule'),
        ),
    ]
