# Generated by Django 3.0.7 on 2020-08-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventpage', '0025_auto_20200820_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
