# Generated by Django 3.2 on 2021-04-24 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventpage', '0026_auto_20200823_0133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='html',
            new_name='markdown',
        ),
    ]
