# Generated by Django 2.2.24 on 2021-08-09 11:47

from django.db import migrations
import django_tuieditor.models


class Migration(migrations.Migration):

    dependencies = [
        ('eventpage', '0027_rename_html_announcement_markdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='markdown',
            field=django_tuieditor.models.MarkdownField(),
        ),
    ]
