# Generated by Django 2.2.15 on 2020-08-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
    ]
