# Generated by Django 2.2.15 on 2020-08-14 01:05

from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='_description_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_markup_type',
            field=models.CharField(blank=True, choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=markupfield.fields.MarkupField(blank=True, null=True, rendered_field=True),
        ),
    ]
