# Generated by Django 2.2.15 on 2020-08-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20200814_0305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='_description_rendered',
            new_name='_description_de_rendered',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='description',
            new_name='description_de',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='description_markup_type',
        ),
        migrations.AddField(
            model_name='partner',
            name='description_de_markup_type',
            field=models.CharField(choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain'), ('markdown', 'Markdown')], default='markdown', max_length=30),
        ),
    ]
