# Generated by Django 2.2.15 on 2020-08-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20200814_0305'),
    ]

    operations = [
    ]
