# Generated by Django 2.2.15 on 2020-08-14 01:24

from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_auto_20200814_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='_description_en_rendered',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_en',
            field=markupfield.fields.MarkupField(blank=True, null=True, rendered_field=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_en_markup_type',
            field=models.CharField(choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain'), ('markdown', 'Markdown')], default='markdown', max_length=30),
        ),
    ]
