# Generated by Django 2.2.15 on 2020-08-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_auto_20200814_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='description_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='partner',
            name='description'
        ),
    ]
