# Generated by Django 2.2.15 on 2020-08-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_partner_hide'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='description_de_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_en_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
