# Generated by Django 3.0.7 on 2020-08-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_auto_20200814_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='slug',
            field=models.SlugField(blank=True, max_length=35, null=True),
        ),
    ]
