# Generated by Django 2.2.24 on 2021-08-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_partner_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='is_project',
            field=models.BooleanField(default=False),
        ),
    ]
