# Generated by Django 3.0.8 on 2020-08-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200814_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.CharField(default='lobby', max_length=30),
            preserve_default=False,
        ),
    ]
