# Generated by Django 3.0.7 on 2020-08-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('SYS', 'system'), ('MSG', 'message'), ('WPR', 'whisper')], default='MSG', max_length=3),
        ),
    ]
