# Generated by Django 3.0.7 on 2020-08-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20200816_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('SYS', 'system_message'), ('MSG', 'chat_message'), ('WPR', 'whisper_message')], default='MSG', max_length=3),
        ),
    ]
