# Generated by Django 3.0.7 on 2020-08-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_bans_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='bans',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
