# Generated by Django 3.2 on 2021-04-21 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_rename_bans_model_to_ban'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Connection',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.RenameField(
            model_name='ban',
            old_name='user',
            new_name='user_name',
        ),
    ]
