# Generated by Django 3.2 on 2021-04-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20210421_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ban',
            name='user_name',
            field=models.CharField(max_length=64),
        ),
    ]
