# Generated by Django 2.2.15 on 2020-08-13 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('secret', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'BigBlueButton Server',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('welcome_msg', models.TextField(blank=True, null=True, verbose_name='Welcome message')),
                ('max_participants', models.IntegerField(default=100)),
                ('record', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='room-logos', verbose_name='Room branding')),
                ('slides', models.FileField(blank=True, null=True, upload_to='room-logos', verbose_name='Default slides')),
                ('start_as_guest', models.BooleanField(default=True, verbose_name='Allow guests to start the conference')),
                ('mute_on_start', models.BooleanField(default=True, verbose_name='Join muted')),
                ('lock_mics', models.BooleanField(default=False, verbose_name='Lock microphones')),
                ('lock_cams', models.BooleanField(default=False, verbose_name='Lock cameras')),
                ('lock_private_chat', models.BooleanField(default=False, verbose_name='Lock private chat')),
                ('lock_public_chat', models.BooleanField(default=False, verbose_name='Lock public chat')),
                ('lock_shared_notes', models.BooleanField(default=False, verbose_name='Lock shared notes')),
                ('lock_layout', models.BooleanField(default=False, verbose_name='Lock layout')),
                ('moderator_pw', models.CharField(blank=True, max_length=100, null=True)),
                ('attendee_pw', models.CharField(blank=True, max_length=100, null=True)),
                ('guest_policy', models.CharField(choices=[('ALWAYS_ACCEPT', 'Always accept'), ('ALWAYS_DENY', 'Always deny'), ('ASK_MODERATOR', 'Ask moderator')], default='ALWAYS_ACCEPT', max_length=30, verbose_name='Guest policy')),
                ('moderators', models.ManyToManyField(blank=True, related_name='teaching', to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbb.Server')),
            ],
            options={
                'verbose_name': 'BigBlueButton Room',
            },
        ),
    ]
