# Generated by Django 2.2.15 on 2020-08-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbb', '0004_auto_20200813_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='for_workshops',
            field=models.BooleanField(default=False),
        ),
    ]
