# Generated by Django 2.2.15 on 2020-08-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbb', '0005_server_for_workshops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='start_as_guest',
            field=models.BooleanField(default=False, verbose_name='Allow guests to start the conference'),
        ),
    ]
