# Generated by Django 2.2.15 on 2020-08-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbb', '0006_auto_20200813_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='hangout_room',
            field=models.BooleanField(default=False),
        ),
    ]
