# Generated by Django 3.0.8 on 2020-08-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbb', '0008_room_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='yolomode',
            field=models.BooleanField(default=False, verbose_name='YOLO MODE'),
        ),
    ]
