# Generated by Django 3.0.8 on 2020-08-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbb', '0011_auto_20200818_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='live',
            field=models.BooleanField(default=False, verbose_name='Live'),
        ),
    ]
