# Generated by Django 2.2.24 on 2021-08-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbb', '0012_room_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='hangout_order',
            field=models.IntegerField(default=9000),
        ),
    ]
